# Docker compose file to manage all the components in the application
#  The docker-compose app will create a "user-defined" network bridge for the applications to connect over.
#
#  All Container names should be prefixed with "portfolio-tracker-" to prevent overlap with other applications

version: '3'
services:
   # need to set up a way to do configuration
   influxdb:
      container_name: portfolio-tracker-influxdb
      image: influxdb
      restart: unless-stopped
      #network_mode: bridge
      ports:
         - "8086:8086"
      volumes:
         - ${PORTFOLIO_TRACKER_DIR}/influxdb:/var/lib/influxdb
         - /home/wallace/portfolio-tracker/config:/docker-entrypoint-initdb.d

   # need to set up a way to do configuration
   mariadb:
     container_name: portfolio-tracker-mariadb
     image: mariadb
     restart: unless-stopped
     env_file:
       - config/container.env
     ports:
       - "3306:3306"
     volumes:
       - ${PORTFOLIO_TRACKER_DIR}/mysql:/var/lib/mysql
       - /home/wallace/portfolio-tracker/config:/docker-entrypoint-initdb.d

   redis:
     container_name: portfolio-tracker-redis
     image: redis
     restart: unless-stopped
     ports:
       - "6379:6379"

#   ptapp:
#     container_name: portfolio-tracker-flask
#     build:
#       context: "."
#       dockerfile: ptapp.dockerfile
#     ports:
#       - "8000:8000"

   grafana:
      container_name: portfolio-tracker-grafana
      image: grafana/grafana
      restart: unless-stopped
      #network_mode: bridge
      ports:
         - "3000:3000"
      user: "1000:1000"
      volumes:
         - ${PORTFOLIO_TRACKER_DIR}/grafana:/var/lib/grafana
         - /home/wallace/portfolio-tracker/config/grafana:/etc/grafana/
