# Docker compose file to manage all the components in the application
#  The docker-compose app will create a "user-defined" network bridge for the applications to connect over. 
#
#  All Container names should be prefixed with "portfolio-tracker-" to prevent overlap with other applications

version: '3'
services:
   influxdb:
      container_name: portfolio-tracker-influxdb
      image: influxdb
      restart: unless-stopped
      #network_mode: bridge 
      ports:
         - "8086:8086"
      volumes:
         - /dockerpersist/portfolio-tracker/influxdb:/var/lib/influxdb

   grafana:
      container_name: portfolio-tracker-grafana
      image: grafana/grafana
      restart: unless-stopped
      #network_mode: bridge
      ports:
         - "3000:3000"
      user: "1000:1000"
      volumes:
         - /dockerpersist/portfolio-tracker/grafana:/var/lib/grafana

