redis:
  hostname: 192.168.0.250
  port: 6379
  databaseId: 0

influxdb:
  hostname: 192.168.0.250
  port: 8086
  databaseName: stockticker

mariadb:
  hostname: 192.168.0.250
  port: 3306
  username: stocksdb_user
  password: stocksdb_password
  database: stocksdb
