# Generated by Django 3.0.5 on 2020-05-16 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_id', models.CharField(max_length=22)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_id', models.CharField(max_length=32)),
                ('routing_number', models.CharField(max_length=9)),
                ('currency_symbol', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('cash', 'Cash Account'), ('cd', 'Certificate of Deposit'), ('bond', 'Bond'), ('stock', 'Stock')], default='cash', max_length=6)),
                ('accountActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashAccounts',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Accounts')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
            bases=('main.accounts',),
        ),
        migrations.CreateModel(
            name='AccountAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('memo', models.CharField(max_length=255)),
                ('ftid', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.CashAccounts')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.UniqueConstraint(fields=('account', 'ftid'), name='unique transaction'),
        ),
    ]
