# Generated by Django 3.0.5 on 2020-07-22 04:47

from django.db import migrations, models
import django.db.models.deletion
import main.types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_id', models.CharField(max_length=22)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_id', models.CharField(max_length=32)),
                ('routing_number', models.CharField(max_length=9)),
                ('currency_symbol', models.CharField(max_length=3)),
                ('type', models.IntegerField(choices=[(1, 'BANK_TYPE'), (2, 'INVESTMENT_TYPE')], default=main.types.AccountTypes['BANK_TYPE'])),
                ('accountActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashAccounts',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Accounts')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('balance_date', models.DateTimeField(null=True)),
            ],
            bases=('main.accounts',),
        ),
        migrations.CreateModel(
            name='InvestmentAccounts',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Accounts')),
                ('position_date', models.DateTimeField(null=True)),
            ],
            bases=('main.accounts',),
        ),
        migrations.CreateModel(
            name='AccountAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftid', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'BUY_DEBT'), (2, 'BUY_MF'), (3, 'BUY_OPT'), (4, 'BUY_OTHER'), (5, 'BUY_STOCK'), (6, 'CLOSURE_OPT'), (7, 'INCOME'), (8, 'INV_EXPENSE'), (9, 'JRNL_FUND'), (10, 'JRNL_SEC'), (11, 'MARGIN_INTEREST'), (12, 'REINVEST'), (13, 'RET_OF_CAP'), (14, 'SELL_DEBT'), (15, 'SELL_MF'), (16, 'SELL_OPT'), (17, 'SELL_OTHER'), (18, 'SELL_STOCK'), (19, 'SPLIT'), (20, 'TRANSFER')], default=main.types.InvestmentTransactionTypes['BUY_OTHER'])),
                ('tradeDate', models.DateTimeField()),
                ('settleDate', models.DateTimeField()),
                ('memo', models.CharField(max_length=255)),
                ('CUSIP', models.CharField(max_length=16)),
                ('ticker', models.CharField(max_length=8)),
                ('income_type', models.IntegerField(choices=[(0, 'NOTINCOME'), (1, 'CGLONG'), (2, 'CGSHORT'), (3, 'DIV'), (4, 'INTEREST'), (5, 'MISC')])),
                ('units', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('comission', models.FloatField(default=0)),
                ('fees', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.InvestmentAccounts')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8)),
                ('CUSIP', models.CharField(max_length=16)),
                ('units', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main.InvestmentAccounts')),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('memo', models.CharField(max_length=255)),
                ('ftid', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.CashAccounts')),
            ],
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.UniqueConstraint(fields=('account', 'ftid'), name='unique investment transaction'),
        ),
        migrations.AddConstraint(
            model_name='investmentposition',
            constraint=models.UniqueConstraint(fields=('account', 'ticker'), name='unique investment position'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.UniqueConstraint(fields=('account', 'ftid'), name='unique cash transaction'),
        ),
    ]
