# Generated by Django 3.0.5 on 2020-04-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_id', models.CharField(max_length=22)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_id', models.CharField(max_length=32)),
                ('routing_number', models.CharField(max_length=9)),
                ('currency_symbol', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('cash', 'Cash Account'), ('cd', 'Certificate of Deposit'), ('bond', 'Bond'), ('stock', 'Stock')], default='cash', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='FileImportAccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=22)),
                ('routing_number', models.CharField(max_length=9)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_id', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('cash', 'Cash Account'), ('cd', 'Certificate of Deposit'), ('bond', 'Bond'), ('stock', 'Stock')], default='cash', max_length=6)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=13)),
                ('balance_date', models.DateTimeField()),
                ('currency_symbol', models.CharField(max_length=3)),
                ('matched', models.BooleanField(default=False)),
                ('matched_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='AccountAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
            ],
        ),
    ]
