# Generated by Django 3.0.5 on 2020-04-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='type',
            field=models.CharField(choices=[('cash', 'Cash Account'), ('cd', 'Certificate of Deposit'), ('bond', 'Bond'), ('stock', 'Stock')], default='cash', max_length=6),
        ),
    ]
