# Generated by Django 3.0.5 on 2020-05-04 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('memo', models.CharField(max_length=255)),
                ('ftid', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.Accounts')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.UniqueConstraint(fields=('account', 'ftid'), name='unique transaction'),
        ),
    ]
