# Generated by Django 3.0.5 on 2020-07-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='comission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='units',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashaccounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='cashaccounts',
            name='balance_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='units',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='income_type',
            field=models.IntegerField(choices=[(0, 'NOTINCOME'), (1, 'CGLONG'), (2, 'CGSHORT'), (3, 'DIV'), (4, 'INTEREST'), (5, 'MISC')]),
        ),
    ]
