# Generated by Django 3.0.5 on 2020-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportaccountdata',
            name='friendlyName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
