# Generated by Django 3.0.5 on 2020-05-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200504_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='accountActive',
            field=models.BooleanField(default=True),
        ),
    ]
