# Generated by Django 3.0.5 on 2020-07-20 00:56

from django.db import migrations, models
import main.types


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200719_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='type',
            field=models.IntegerField(choices=[(1, 'BANK_TYPE'), (2, 'INVESTMENT_TYPE')], default=main.types.AccountTypes['BANK_TYPE']),
        ),
    ]
