# Generated by Django 3.0.5 on 2020-07-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200720_0056'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='investmentposition',
            constraint=models.UniqueConstraint(fields=('account', 'ticker'), name='unique investment position'),
        ),
    ]
