# Generated by Django 3.0.5 on 2020-07-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200720_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentaccounts',
            name='position_date',
            field=models.DateTimeField(null=True),
        ),
    ]
