# Generated by Django 3.0.5 on 2020-07-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200720_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentposition',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='comission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
