# Generated by Django 3.0.5 on 2020-04-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('fileid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendlyName', models.CharField(max_length=200)),
                ('account_id', models.CharField(max_length=22)),
                ('routing_number', models.CharField(max_length=9)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_id', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('cash', 'Cash Account'), ('cd', 'Certificate of Deposit'), ('bond', 'Bond'), ('stock', 'Stock')], default='cash', max_length=6)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=13)),
                ('balance_date', models.DateTimeField()),
                ('currency_symbol', models.CharField(max_length=3)),
                ('matched', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='imports.FileData')),
                ('matched_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_account', to='main.Accounts')),
            ],
        ),
    ]
