# Generated by Django 3.0.5 on 2020-07-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='comission',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='fees',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='income_type',
            field=models.IntegerField(choices=[(0, 'NOTINCOME'), (1, 'CGLONG'), (2, 'CGSHORT'), (3, 'DIV'), (4, 'INTEREST'), (5, 'MISC')]),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='units',
            field=models.FloatField(default=0),
        ),
    ]
